projects:
  todo:
    schemaPath: graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: build/API.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
